version: '3'

networks:
  proxy:
    external: true

volumes:
  nginx_data:
    name: nginx_data
  nginx_letsencrypt:
    name: nginx_letsencrypt

services:
  nginx:
    container_name: nginx
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # Disable in production
      - '443:443'
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - proxy
