version: '3.8'

volumes:
  redis-stack-data:
    name: redis-stack-data

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    env_file:
      - .env
    ports:
      - "6379:6379" # Redis port
      - "8001:8001" # Redis stack UI port
    volumes:
      - redis-stack-data:/data # Bind mount a volume for persistent data storage
    environment:
      - REDIS_ARGS=--requirepass $REDIS_PASSWORD # Set password using environment variable
    restart: unless-stopped # Ensure the container restarts unless manually stopped
