
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    env_file:
      - .env
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-stack-data:/data 
    environment:
      REDIS_ARGS: >
        --requirepass ${REDIS_PASSWORD}
        --maxmemory 64mb
        --maxmemory-policy allkeys-lru
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M 

volumes:
  redis-stack-data:
    name: redis-stack-data
